ExUnit.start()
Mox.defmock(BotArmyGtd.TaskStoreMock, for: BotArmyGtd.TaskStoreBehaviour)
Mox.defmock(BotArmyGtd.ProjectStoreMock, for: BotArmyGtd.ProjectStoreBehaviour)
Mox.defmock(BotArmyGtd.InboxItemStoreMock, for: BotArmyGtd.InboxItemStoreBehaviour)
Mox.defmock(BotArmyGtd.DecompositionStoreMock, for: BotArmyGtd.DecompositionStoreBehaviour)
Mox.defmock(BotArmyGtd.MockLogEntryStore, for: BotArmyGtd.LogEntryStoreBehaviour)
